//This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://skadvjxqxkcdyeccywsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrYWR2anhxeGtjZHllY2N5d3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTE2MjUsImV4cCI6MjA2ODgyNzYyNX0.61OVQ_V0DPWIil1M51DAxktIPz2tS2RFbhaaQ9cDMWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
